#pragma once

// WINDOWS
#define WINDOW_HEIGHT 720
#define WINDOW_WIDTH 1280

// TEXT
#define TEXT_SIZE 28

// TEXT HISTORY
#define TEXT_HISTORY_BUFFER_SIZE 24
#define TEXT_HISTORY_SPACING_Y 28
#define TEXT_HISTORY_PADDING_X 16
#define TEXT_HISTORY_PADDING_Y 16
#define TEXT_HISTORY_WIDTH 800
#define TEXT_HISTORY_HEIGHT 600
#define TEXT_HISTORY_X 240
#define TEXT_HISTORY_Y 0

// TEXT INPUT
#define TEXT_INPUT_X 240
#define TEXT_INPUT_Y 610
#define TEXT_INPUT_PADDING_X 16
#define TEXT_INPUT_PADDING_Y 16